apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-app-deployment
  labels:
    app: api-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-app
  template:
    metadata:
      labels:
        app: api-app
    spec:
      nodeSelector:
        "kubernetes.io/os": windows
      containers:
        - name: mvc-app
          image: __acr_name__/__repository__:__Build.BuildId__
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: api-app-loadbalancer-service
  labels:
    app: api-app
spec:
  type: LoadBalancer
  selector:
    app: api-app
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP