apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app-deployment
  labels:
    app: java-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: java-app
          image: __acr_name__/__repository__:__Build.BuildId__
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: java-app-loadbalancer-service
  labels:
    app: java-app
spec:
  type: LoadBalancer
  selector:
    app: java-app
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP